# Generated by Django 5.0.1 on 2024-01-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='date',
            field=models.DateField(default='2023-01-15'),
            preserve_default=False,
        ),
    ]
